### ISSUE TITLE
Use Case: Show information about a patient

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/timeline#1]
We would like to show all information about a patient in a timeline, where the patient is selected in advance and all information about him is rendered from a mock api call. Information should be displayed in a timeline and different types of information should be easy to distinguish. Information displayed should be searchable with a search bar on the top right corner.

This project is decomposed in Epic main Issues
- [x] Boiler plate with a white page but using next.js
- [ ] Load information about a given patient using a mock API #6 
- [ ] Display basic information about patient #2
- [ ] Add elements on the timeline which are distinguishable and clickable #3
- [ ] Add a search bar to find specific information about the patient #4 
- [ ] Group elements which happen all at the same moment #5
