### ISSUE TITLE
Add elements on the timeline which are distinguishable and clickable

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/timeline#3]
Part of project #1 
Display information on a timeline
- [ ] Choose and display and empty timeline
- [ ] Create components for each type of information, which are easy to distinguish, with simple and additional info
- [ ] Put the component on the timeline and make them clickable
