### ISSUE TITLE
Add a search bar to find specific information about the patient

### ISSUE THREAD

**Issue by LaRiffle** [arkhn/timeline#4]
Part of project #1
- [ ] Create a search bar component
- [ ] Allow search across all the patient data
- [ ] Display results with links to the component on the timeline
